package com.example.ami.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * One day's wellbeing reading.
 *
 * Keyed by epoch day rather than by an autogenerated id: there is exactly one reading
 * per calendar day, and writing a second one for the same day should correct the first
 * rather than stack a duplicate the trend would then count twice.
 *
 * The three stored dimensions are the ones a person can actually answer for themselves.
 * Burnout and overall wellbeing are *not* stored - they are read out of these by
 * [com.example.ami.wellbeing.WellbeingStory], because a derived number that is also
 * persisted is a number that can disagree with the data it came from.
 */
@Entity(tableName = "wellbeing_entries")
data class WellbeingEntry(
    @PrimaryKey val epochDay: Long,
    /** 0-100, **higher is worse**. The one inverted scale here; see [SCALE_MAX]. */
    val stress: Int,
    /** 0-100, higher is better. */
    val sleep: Int,
    /** 0-100, higher is better. */
    val social: Int,
    /** People actually spoken to that day. A count, not a score. */
    val connections: Int = 0
) {
    /**
     * All three dimensions on a "higher is better" footing, which is what the composite
     * wellbeing figure needs. Stress is the odd one out and gets flipped.
     */
    val positiveStress: Int get() = SCALE_MAX - stress

    companion object {
        const val SCALE_MIN = 0
        const val SCALE_MAX = 100

        fun clamp(value: Int): Int = value.coerceIn(SCALE_MIN, SCALE_MAX)
    }
}
